apiVersion: v1
kind: Service
metadata:
  labels:
    app: fetch
  name: fetch-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32524
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: fetch
  type: LoadBalancer
